import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Chatbot from "@/components/chatbot";
import { getServerDarkMode } from "@/hooks/use-server-dark-mode";
import ClientCookiesProvider from "@/components/client-cookies-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: {
    template: '%s | Krishn Patel',
    default: 'Krishn Patel'
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const theme = await getServerDarkMode()
  return (
    <html lang="en" data-theme={theme}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientCookiesProvider>
        <Header />
        <main className="mt-12">{children}</main>
        <Chatbot />
        </ClientCookiesProvider>
      </body>
    </html>
  );
}
